sudo: required

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - docker compose up
  - mvn clean package -DskipTests
  - docker build -t kacperkwiatkowski/backend-tweet -f Dockerfile .

script:
  - docker images
