sudo: true

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - echo $MAIL_USERNAME
  - echo $MAIL_PASSWORD
  - chmod +x mvnw
  - docker-compose -f "docker-compose-test.yml" up -d
  - mvn clean package
#  - docker build --build-arg MAIL_USERNAME=$MAIL_USERNAME --build-arg MAIL_PASSWORD=$MAIL_PASSWORD -t kacperkwiatkowski/backend-tweet -f Dockerfile .
script:
  - docker images


#docker compose -f "docker-compose-prod.yml" build --build-arg "MAIL_USERNAME=kacper.kwiatkowski.cognizant@gmail.com" --build-arg "MAIL_PASSWORD=sdxoujxpdyoytduu"
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: tweet-app
  env: Tweetapp-env
  bucket_name: elasticbeanstalk-eu-central-1-007555715517
  bucket_path: tweet-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  MAIL_USERNAME: $MAIL_USERNAME
  MAIL_PASSWORD: $MAIL_PASSWORD