sudo: required

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - mvn clean package -DskipTests=true
  - docker build -t kacperkwiatkowski/backend-tweet -f Dockerfile .
  - docker-compose build up

script:
  - docker images
