sudo: true

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - chmod +x mvnw
  - docker-compose -f "docker-compose-test.yml" up -d

script:
  - mvn clean test

after_success:
  - docker build -t kacperkwiatkowski/backend-tweet ./
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kacperkwiatkowski/backend-tweet
