sudo: required

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - docker-compose up -d mongo-tweets
  - mvn clean package -DskipTests=true
  - docker build -t kacperkwiatkowski/backend-tweet -f Dockerfile .
  - mvn test

script:
  - docker images
