sudo: true

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - chmod +x mvnw
  - docker-compose -f "docker-compose-test.yml" up -d

script:
  - mvn clean test

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: tweet-app
  env: Tweetapp-env-1
  bucket_name: elasticbeanstalk-eu-central-1-007555715517
  bucket_path: tweet-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY