sudo: true

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
  - aws --version
  - chmod +x mvnw
  - docker-compose -f "docker-compose-test.yml" up -d

script:
  - mvn clean test

after_success:
  - docker build -t kacperkwiatkowski/backend-tweet ./
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kacperkwiatkowski/backend-tweet
  - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 195077249767.dkr.ecr.eu-central-1.amazonaws.com
  - docker tag kacperkwiatkowski/backend-tweet 195077249767.dkr.ecr.eu-central-1.amazonaws.com/kacperkwiatkowski/backend-tweet
  - docker push 195077249767.dkr.ecr.eu-central-1.amazonaws.com/kacperkwiatkowski/backend-tweet
