sudo: required

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - docker-compose -f "docker-compose-test.yml" up -d
  - mvn clean package -DskipTests=true
  - docker build -t kacperkwiatkowski/backend-tweet -f Dockerfile .
  - mvn test

script:
  - docker images
