sudo: true

language: java

jdk: oraclejdk17

services:
  - docker

before_install:
  - chmod +x mvnw
  - docker-compose -f "docker-compose-test.yml" up -d
  - mvn clean package
  - docker build -t kacperkwiatkowski/backend-tweet -f Dockerfile .
script:
  - docker images
