version: '3.9'

services:

  mongo-tweets:
    image: mongo
    container_name: mongo-tweets
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_username
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    networks:
      - tweets-network

  backend-tweet:
    image: backend-tweet
    container_name: backend-tweet
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-tweets:29092"
      MAIL_USERNAME: mock
      MAIL_PASSWORD: mock
      DB_USERNAME: mongo_username
      DB_PASSWORD: mongo_password
      DB_NAME: mongo-tweets
      DB_HOST: mongo-tweets
      DB_PORT: 27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo-tweets
    restart: always
    networks:
      - tweets-network

networks:
  tweets-network:
    driver: bridge