version: '3.9'

services:

  elasticsearch-tweets:
    image: elasticsearch:7.16.2
    container_name: elasticsearch-tweets
    restart: always
    volumes:
      - elastic-data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: changeme
      xpack.security.enabled: "false"
    ports:
      - '9200:9200'
    networks:
      - elastic-network

  logstash-tweets:
    image: logstash:7.16.2
    container_name: logstash-tweets
    restart: always
    volumes:
      - ./config:/etc/logstash/conf.d
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch-tweets
    ports:
      - '5000:5000'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic-network

  kibana-tweets:
    image: kibana:7.16.2
    container_name: kibana-tweets
    restart: always
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-tweets:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-tweets:9200"]'
    depends_on:
      - elasticsearch-tweets
    networks:
      - elastic-network

volumes:
  elastic-data: {}

networks:
  elastic-network: