version: '3.9'

services:

  dynamodb-tweets:
    image:  amazon/dynamodb-local
    container_name: dynamodb-tweets
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

  zookeeper-tweets:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-tweets
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    restart: "no"

  kafka-tweets:
    image: bitnami/kafka:latest
    container_name: kafka-tweets
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka-tweets:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-tweets:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
      - "29092:29092"
    restart: "no"
    depends_on:
      - zookeeper-tweets

  backend-tweet:
    image: backend-tweet
    container_name: backend-tweet
    build:
      context: ./
      dockerfile: Dockerfile.prod
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-tweets:29092"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
    ports:
      - "8080:8080"
    depends_on:
      - kafka-tweets
      - dynamodb-tweets
    restart: always

    env_file:
      - .env