version: '3.9'

services:

  backend-tweet:
    image: backend-tweet
    container_name: backend-tweet
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-tweets:29092"
      MAIL_USERNAME: mock
      MAIL_PASSWORD: mock
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - mongo-tweets
    restart: always
    networks:
      - tweets-network

networks:
  tweets-network:
    driver: bridge