version: '3.9'

services:

  dynamodb-tweets:
    image:  amazon/dynamodb-local
    container_name: dynamodb-tweets
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

  backend-tweet:
    image: backend-tweet
    container_name: backend-tweet
    build:
      context: ./
      dockerfile: Dockerfile.prod
    environment:
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-tweets
    restart: always

    env_file:
      - .env