server:
  servlet:
    context-path: /api/v.1.0/tweets

spring:

  main:
    banner-mode: off

  application:
    name: TWEET-SERVICE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  data:
    mongodb:
      authentication-database: admin
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      database: ${DB_NAME}
      port: ${DB_PORT}
      host: ${DB_HOST}

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

application:
  jwt:
    secret-key: securesecuresecuresecuresecuresecuresecure
    token-prefix: Bearer
    token-expiration-after-days: 14

mail:
  username: mock
  password: mock

