server:
  servlet:
    context-path: /api/v.1.0/tweets

spring:

  config:
    import: file:env.properties

  main:
    banner-mode: off

  application:
    name: tweet-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


application:
  jwt:
    secret-key: securesecuresecuresecuresecuresecuresecure
    token-prefix: Bearer
    token-expiration-after-days: 14

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

topic:
  forgottenPassword: forgottenPassword

time:
  format:
    pattern: 'dd.MM.yyyy HH:mm:ss:SSS'

amazon:
  region: eu-central-1
  dynamodb:
    endpoint: http://localhost:8000/
  sqs:
    endpoint: https://sqs.eu-central-1.amazonaws.com/195077249767/

aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretAccessKey: ${AWS_SECRET_KEY}