server:
  servlet:
    context-path: /api/v.1.0/tweets

spring:

  config:
    import: file:env.properties

  main:
    banner-mode: off

  application:
    name: tweet-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "default"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    streams:
      auto-startup: false

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


application:
  jwt:
    secret-key: securesecuresecuresecuresecuresecuresecure
    token-prefix: Bearer
    token-expiration-after-days: 14

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

topic:
  forgottenPassword: forgottenPassword

time:
  format:
    pattern: 'dd.MM.yyyy HH:mm:ss:SSS'

amazon:
  region: eu-central-1
  dynamodb:
    endpoint: https://dynamodb.eu-central-1.amazonaws.com
  sqs:
    endpoint: https://sqs.eu-central-1.amazonaws.com/195077249767/

aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretAccessKey: ${AWS_SECRET_KEY}