server:
  servlet:
    context-path: /api/v.1.0/tweets

spring:

  main:
    banner-mode: off

  application:
    name: TWEET-SERVICE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

application:
  jwt:
    secret-key: securesecuresecuresecuresecuresecuresecure
    token-prefix: Bearer
    token-expiration-after-days: 14

mail:
  username: mock
  password: mock

amazon:
  dynamodb:
    endpoint: https://dynamodb.eu-central-1.amazonaws.com
    region: eu-central-1
  aws:
    accesskey: ${AWS_ACCESS_KEY}
    secretkey: ${AWS_SECRET_KEY}
