server:
  servlet:
    context-path: /api/v.1.0/tweets

spring:

  codec:
    max-in-memory-size: 10MB

  main:
    banner-mode: off

  application:
    name: TWEET-SERVICE

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "default"

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


application:
  jwt:
    secret-key: securesecuresecuresecuresecuresecuresecure
    token-prefix: Bearer
    token-expiration-after-days: 14

topic:
  forgottenPassword: user.password.forgotten

mail:
  username: mock
  password: mock

time:
  format:
    pattern: 'dd.MM.yyyy HH:mm:ss:SSS'

amazon:
  dynamodb:
    endpoint: https://dynamodb.eu-central-1.amazonaws.com
    region: eu-central-1
  aws:
    accesskey: ${AWS_ACCESS_KEY}
    secretkey: ${AWS_SECRET_KEY}
