package com.kacperKwiatkowski.tweetApp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.UUID;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@DynamoDBTable(tableName = "like")
public class LikeEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID likeId;
    @DynamoDBAttribute
    private String username;
    @DynamoDBAttribute
    private UUID tweetId;
}
