package com.kacperKwiatkowski.tweetApp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.kacperKwiatkowski.tweetApp.security.role.RoleType;
import lombok.*;

import java.util.UUID;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@DynamoDBTable(tableName = "user")
public class UserEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;
    @DynamoDBAttribute
    private String firstName;
    @DynamoDBAttribute
    private String lastName;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String username;
    @DynamoDBAttribute
    private String contactNumber;
    @DynamoDBAttribute
    private byte[] avatar;
    @DynamoDBAttribute
    private String password;
    @DynamoDBAttribute
    private String roleType;

    public UUID getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute
    public String getUsername() {
        return username;
    }

    @DynamoDBAttribute
    public String getContactNumber() {
        return contactNumber;
    }

    @DynamoDBAttribute
    public byte[] getAvatar() {
        return avatar;
    }

    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }

    @DynamoDBAttribute
    public String getRoleType() {
        return roleType;
    }

    public UserEntity assignRole() {
        this.roleType = RoleType.USER.toString();
        return this;
    }
}
